# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod

spring:
  profiles:
    active: test
  http:
     encoding:
        force: true
        enabled: true
        charset: utf8
     multipart:
        maxFileSize: 10Mb
        maxRequestSize: 100Mb
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  mail:
    host: smtp.exmail.qq.com
    username: service@mail.cn
    password: myPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  login:
    whiteList: /user/login;*.js

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  tomcat:
      uriEncoding: UTF-8
  port: 8088
management:
  port: 54001
  health:
    mail:
      enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
